[versions]
kotlin = "1.8.20"
kord = "0.8.2"
koin = "3.4.0"

[libraries]
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
sl4fj-simple = "org.slf4j:slf4j-simple:2.0.7"
dotenv-kotlin = "io.github.cdimascio:dotenv-kotlin:6.4.1"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines", version.ref = "koin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }