[versions]
kotlin = "1.8.20"
kord = "0.8.2"
koin = "3.4.0"

[libraries]
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
dotenv-kotlin = "io.github.cdimascio:dotenv-kotlin:6.4.1"
logback-classic = "ch.qos.logback:logback-classic:1.4.5"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines", version.ref = "koin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }